#version 450 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 2)
buffer cellStartBuffer
{
    uint cellStart[];
};

layout(std430, binding = 3)
buffer cellEndBuffer
{
    uint cellEnd[];
};

layout(std430, binding = 4)
buffer CounterBuffer
{
    uint cellCount;
};

uniform int activeCount;

int GetIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, uint _count){
    if(_id >= int(_count))
        return false;
    return true;
}

void main()
{
    int id = GetIndex();
    if(!WithinBounds(id, cellCount))
        return;

    if(id == cellCount - 1)
    {
        cellEnd[id] = activeCount;
    }
    else
    {
        cellEnd[id] = cellStart[id+1];
    }
}