#version 450 core

layout (local_size_x = 10, local_size_y = 1, local_size_z = 1) in;

struct HashEntry{
    uint hash;
    uint particleIndex;
};
layout(std430, binding = 1)
buffer hashBuffer {
    HashEntry hashes[];
};

layout(std430, binding = 6)
buffer cellFlagBuffer {
    uint cellFlags[];
};

layout(std430, binding = 7)
buffer cellPrefixBuffer {
    uint cellScan[];
};

uniform int activeCount;

int GetIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, int _count){
    if(_id >= _count)
        return false;
    return true;
}

void main() {
    
    int id = GetIndex();

    if(!WithinBounds(id, cellFlags.length()))
        return;
    
    if(!WithinBounds(id, activeCount)){
        cellFlags[id] = 0;
        cellScan[id] = 0;
        return;
    }

    if(id == 0 || hashes[id].hash != hashes[id-1].hash)
    {
        cellFlags[id] = 1;
        cellScan[id] = 1;
    }
    else
    {
        cellFlags[id] = 0;
        cellScan[id] = 0;
    }
}