#version 450 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct HashLookupEntry{
    uint hash;
    uint cellIndex;
};
layout(std430, binding = 8)
buffer LookupBuffer
{
    HashLookupEntry lookup[];
};

int GetCellIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, int _count){
    if(_id >= _count)
        return false;
    return true;
}

void main()
{
    int cell = GetCellIndex();
    if (!WithinBounds(cell, lookup.length()))
        return;

    lookup[cell].hash = 0xffffffff;
    lookup[cell].cellIndex = 0xffffffff;
}