#version 450 core

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct HashEntry{
    uint hash;
    uint index;
};
layout(std430, binding = 1) buffer entryBuffer {
    HashEntry hashEntrys[];
};

const uint INVALID = 0xffffffffu;
uniform int k;
uniform int j;

int GetIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, int _count){
    if(_id >= _count)
        return false;
    return true;
}

void main() {
    
    int id = GetIndex();
    if(!WithinBounds(id, hashEntrys.length()))
        return;

    // Useses bitwise XOR to find partner
    // Example id = 5 = 0101
    // Exmaple j = 4 = 0100
    // Exmaple partner = 1 = 0001
    int partner = id ^ j; 

    // end early if overlappign sort, 4 sort with 0 and 0 sort with 4, so lower bounds is droped.
    if(id > partner)
        return;

    // Bitonic sort goes 1234321 for optiomal sorting, this makes sure this happens. 
    bool ascending = ((id & k) == 0);

    if(ascending)
    {
        if(hashEntrys[id].hash > hashEntrys[partner].hash){
            HashEntry temp = hashEntrys[id];
            hashEntrys[id] = hashEntrys[partner];
            hashEntrys[partner] = temp;
        }
    } else {
        if(hashEntrys[id].hash < hashEntrys[partner].hash){
            HashEntry temp = hashEntrys[id];
            hashEntrys[id] = hashEntrys[partner];
            hashEntrys[partner] = temp;
        }
    }

}