#version 450 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 7) buffer cellPrefixBuffer {
    uint cellPrefixes[];
};

uniform int stride;

int GetIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, int _count){
    if(_id >= _count)
        return false;
    return true;
}

void main() {
    
    int id = GetIndex();
    int index = (id + 1) * stride * 2 - 1;
    if(!WithinBounds(index, cellPrefixes.length()))
        return;

    cellPrefixes[index] += cellPrefixes[index - stride];
}