#version 450 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct HashEntry{
    uint hash;
    uint index;
};
layout(std430, binding = 1) readonly buffer entryBuffer {
    HashEntry hashEntrys[];
};

layout(std430, binding = 6) writeonly buffer cellFlagBuffer {
    uint cellFlags[];
};

layout(std430, binding = 7) writeonly buffer cellPrefixBuffer {
    uint cellPrefixes[];
};

const uint INVALID = 0xffffffffu;
uniform int activeCount;

int GetIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, int _count){
    if(_id >= _count)
        return false;
    return true;
}

void main() {
    
    int id = GetIndex();

    if(!WithinBounds(id, cellFlags.length()))
        return;
    
    if(!WithinBounds(id, activeCount)){
        cellFlags[id] = 0;
        cellPrefixes[id] = 0;
        return;
    }

    if(id == 0 || hashEntrys[id].hash != hashEntrys[id-1].hash)
    {
        cellFlags[id] = 1;
        cellPrefixes[id] = 1;
    }
    else
    {
        cellFlags[id] = 0;
        cellPrefixes[id] = 0;
    }
}