#version 450 core
#define PI 3.14159265359

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

struct DDARay{
    ivec3 cell;
    ivec3 step;
    vec3 tMax;
    vec3 tDelta;
    float t;
};

struct Camera{
    vec3 position;
    vec3 up;
    vec3 right;
    vec3 front;
    float fov;
    float maxRayLength;
};

struct Sphere{
    vec3 position;
    float radius;
};

struct Particle{
    vec3 position;
    float radius;
    vec3 velocity;
    float mass;
    vec4 color;
};

struct HashEntry{
    uint hash;
    uint particleIndex;
};

struct HashLookupEntry{
    uint hash;
    uint cellIndex;
};

// Image binding
layout (rgba32f, binding = 0) uniform image2D imgOutput;
// Texture binding
layout(binding = 0) uniform samplerCube skybox;
// SSBO binding
layout(std430, binding = 0) buffer particleBuffer {Particle particles[];};
layout(std430, binding = 1) buffer hashBuffer { HashEntry hashes[]; };
layout(std430, binding = 2) buffer cellStartBuffer { uint cellStart[]; };
layout(std430, binding = 3) buffer cellEndBuffer { uint cellEnd[]; };
layout(std430, binding = 8) buffer LookupBuffer { HashLookupEntry lookup[]; };
// Uniform binding
uniform float cellSize;
uniform float particleRadius;
uniform Camera camera;
uniform Sphere sphere;
// Constants
vec4 blackHoleColor = vec4(0.0, 0.0, 0.0, 1.0);
const int cellRadius = int(ceil(particleRadius / cellSize)); // allows for particle radius to be greater than cell size, although expensive

bool PixelIsInput(vec2 _pixel, vec2 _position)
{
    return _pixel == _position;
}

ivec2 UVToPixel(vec2 _uv, ivec2 _imgSize)
{
    return ivec2(_uv * vec2(_imgSize - 1));
}

ivec2 GetTexelCoordinate()
{
    return ivec2(gl_GlobalInvocationID.xy);
}

bool IsInsideWindow(vec2 _imageSize, ivec2 _texelCord){
    if (_texelCord.x >= _imageSize.x ||
        _texelCord.y >= _imageSize.y)
    {
        return true;
    }
    return false;
}

DDARay InitDDA(vec3 _rayOrigin, vec3 _rayDirection)
{
    DDARay dda;

    vec3 p = _rayOrigin / cellSize;
    dda.cell = ivec3(floor(p));
    if (_rayDirection.x < 0.0 && fract(p.x) == 0.0)
        dda.cell.x--;
    if (_rayDirection.y < 0.0 && fract(p.y) == 0.0)
        dda.cell.y--;
    if (_rayDirection.z < 0.0 && fract(p.z) == 0.0)
        dda.cell.z--;

    // Direction of grid traversal
    dda.step = ivec3(
        _rayDirection.x >= 0.0 ? 1 : -1,
        _rayDirection.y >= 0.0 ? 1 : -1,
        _rayDirection.z >= 0.0 ? 1 : -1
    );

    // Distance along ray between boundries
    dda.tDelta = vec3(
        _rayDirection.x != 0.0 ? abs(cellSize / _rayDirection.x) : 1.0 / 0.0,
        _rayDirection.y != 0.0 ? abs(cellSize / _rayDirection.y) : 1.0 / 0.0,
        _rayDirection.z != 0.0 ? abs(cellSize / _rayDirection.z) : 1.0 / 0.0
    );

    // Find next grid boundry on each axis
    vec3 cellMin = vec3(dda.cell) * cellSize;
    vec3 cellMax = cellMin + cellSize;

    vec3 nextBoundry = vec3(
        dda.step.x > 0 ? cellMax.x : cellMin.x,
        dda.step.y > 0 ? cellMax.y : cellMin.y,
        dda.step.z > 0 ? cellMax.z : cellMin.z
    );

    dda.tMax = vec3(
        _rayDirection.x != 0.0 ? (nextBoundry.x - _rayOrigin.x) / _rayDirection.x : 1.0 / 0.0,
        _rayDirection.y != 0.0 ? (nextBoundry.y - _rayOrigin.y) / _rayDirection.y : 1.0 / 0.0,
        _rayDirection.z != 0.0 ? (nextBoundry.z - _rayOrigin.z) / _rayDirection.z : 1.0 / 0.0
    );

    dda.t = 0.0;

    return dda;
}

void AdvanceDDA(inout DDARay _dda)
{
    if (_dda.tMax.x <= _dda.tMax.y &&
        _dda.tMax.x <= _dda.tMax.z)
    {
        _dda.t = _dda.tMax.x;
        _dda.tMax.x += _dda.tDelta.x;
        _dda.cell.x += _dda.step.x;
    }
    else if (_dda.tMax.y <= _dda.tMax.z)
    {
        _dda.t = _dda.tMax.y;
        _dda.tMax.y += _dda.tDelta.y;
        _dda.cell.y += _dda.step.y;
    }
    else
    {
        _dda.t = _dda.tMax.z;
        _dda.tMax.z += _dda.tDelta.z;
        _dda.cell.z += _dda.step.z;
    }
}

bool RaySphereIntersection(vec3 _rayOrigin, vec3 _rayDirection, Sphere _sphere, float _tMin, float _tMax, out float _hitT)
{
    vec3 oc = _rayOrigin - _sphere.position;

    float b = dot(oc, _rayDirection);
    float c = dot(oc, oc) - _sphere.radius * _sphere.radius;

    float discriminant = b * b - c;

    if(discriminant < 0.0)
        return false;
    
    float sqrtD = sqrt(discriminant);

    float t0 = -b - sqrtD;
    float t1 = -b + sqrtD;

    // find first intersection within cell segement
    float t = t0;

    if(t < _tMin)
        t = t1;
    
    if(t < _tMin || t > _tMax)
        return false;
    
    _hitT = t;
    return true;
}

bool RayAABB(vec3 _rayOrigin, vec3 _rayDirection, vec3 _boxMin, vec3 _boxMax, float _tMin, float _tMax)
{
    vec3 invDir = 1.0 / _rayDirection;

    vec3 t0 = (_boxMin - _rayOrigin) * invDir;
    vec3 t1 = (_boxMax - _rayOrigin) * invDir;

    vec3 tNear = min(t0, t1);
    vec3 tFar  = max(t0, t1);

    float nearT = max(_tMin, max(tNear.x, max(tNear.y, tNear.z)));
    float farT  = min(_tMax, min(tFar.x, min(tFar.y, tFar.z)));

    return nearT <= farT;
}

bool RayCapsuleAABB(vec3 _rayOrigin, vec3 _rayDirection, vec3 _cellMin, vec3 _cellMax, float _tMin, float _tMax, float _radius)
{
    _cellMin -= vec3(_radius);
    _cellMax += vec3(_radius);

    return RayAABB(_rayOrigin, _rayDirection, _cellMin, _cellMax, _tMin, _tMax);
}

vec2 DirectionToUV(vec3 _dir)
{
    float u = atan(_dir.y, _dir.x) / (2.0 * PI) + 0.5;
    float v = asin(_dir.z) / PI + 0.5;

    return vec2(u, v);
}

uint Hash(ivec3 _c)
{
    const uint h1 = 79801u;
    const uint h2 = 62548u;
    const uint h3 = 32193u;
    // XOR ^ mixes the bits togeather better than with addition or othewise, good for hashing.
    return uint(_c.x) * h1 ^ uint(_c.y) * h2 ^ uint(_c.z) * h3;
}

uint FindCell(uint _hash)
{
    uint mask = lookup.length() - 1;
    uint slot = _hash & mask;

    for (uint probe = 0u; probe < lookup.length(); ++probe)
    {
        uint storedHash = lookup[slot].hash;

        // cell does not exist
        if (storedHash == 0xffffffff)
            return 0xffffffff;

        // correct cell
        if (storedHash == _hash)
            return lookup[slot].cellIndex;

        // Collision, try next
        slot = (slot + 1) & mask;
    }
}

bool FindParticleHit(uint _cellIndex, vec3 _rayOrigin, vec3 _rayDirection, float _tMin, float _tMax, inout float _closestHit, inout uint _closestParticle)
{
    uint start = cellStart[_cellIndex];
    uint end   = cellEnd[_cellIndex];

    for (uint i = start; i < end; ++i)
    {
        uint particleIndex = hashes[i].particleIndex;

        if (particleIndex == 0xffffffff)
            continue;

        Sphere particleSphere;
        particleSphere.position = particles[particleIndex].position;
        particleSphere.radius = particles[particleIndex].radius;
        float hitT;
        if (RaySphereIntersection(_rayOrigin, _rayDirection, particleSphere, _tMin, min(_tMax, _closestHit), hitT))
        {
            if (hitT < _closestHit)
            {
                _closestHit = hitT;
                _closestParticle = particleIndex;
            }
        }
    }

    return _closestParticle != 0xffffffff;
}

void SearchNeighbourCells(ivec3 centerCell, vec3 rayOrigin, vec3 rayDirection, float tMin, float tMax, inout float closestHit, inout uint closestParticle)
{
    for (int z = -cellRadius; z <= cellRadius; ++z)
    {
        for (int y = -cellRadius; y <= cellRadius; ++y)
        {
            for (int x = -cellRadius; x <= cellRadius; ++x)
            {
                ivec3 cellPosition =centerCell + ivec3(x, y, z);

                uint cellHash = Hash(cellPosition);
                uint cellIndex = FindCell(cellHash);

                if (cellIndex == 0xffffffffu)
                    continue;

                FindParticleHit(cellIndex, rayOrigin, rayDirection, tMin, tMax, closestHit, closestParticle);
            }
        }
    }
}

void Raytrace(const Camera _camera, vec2 _imageSize, ivec2 _texelCord, vec2 _uv)
{
    // Ray generation
    // ------------------
    vec2 centredUV = (_uv * 2.0) - 1.0;
    float fov = tan(radians(_camera.fov) * 0.5);
    centredUV *= fov;

    float aspect = _imageSize.x / _imageSize.y;
    centredUV.x *= aspect;

    vec3 rayDirection = normalize(
        _camera.front +
        centredUV.x * _camera.right +
        centredUV.y * _camera.up
    );

    vec3 rayOrigin = _camera.position;

    // Black hole intersection
    // --------------------------------
    float blackHoleT;
    bool blackHoleHit = RaySphereIntersection(rayOrigin, rayDirection, sphere, 0.0, _camera.maxRayLength, blackHoleT);

    // DDA initialization
    // -----------------------

    DDARay dda = InitDDA(rayOrigin, rayDirection);

    // Don't search beyond black hole
    float rayEnd = _camera.maxRayLength;

    if (blackHoleHit)
        rayEnd = min(rayEnd, blackHoleT);

    // Traverse grid
    // --------------------
    while (dda.t < rayEnd)
    {
        float cellExitT = min(dda.tMax.x, min(dda.tMax.y, dda.tMax.z));
        cellExitT = min(cellExitT, rayEnd);


        // Search current + neighbouring cells
        // -------------------------------------
        float closestHit = cellExitT;
        uint closestParticle = 0xffffffff;

        SearchNeighbourCells(dda.cell, rayOrigin, rayDirection, dda.t, cellExitT, closestHit, closestParticle);


        // Particle hit
        // -------------------
        if (closestParticle != 0xffffffff)
        {
            imageStore(imgOutput, _texelCord, particles[closestParticle].color);
            return;
        }

        // Black hole reached
        // -----------------------
        if (blackHoleHit && blackHoleT <= cellExitT)
        {
            imageStore(imgOutput, _texelCord, blackHoleColor);
            return;
        }

        // Next grid cell
        // ------------------
        AdvanceDDA(dda);
    }

    // Nothing hit
    // ----------------
    if (blackHoleHit)
    {
        imageStore(imgOutput, _texelCord, blackHoleColor);
        return;
    }

    vec3 skyBoxColour = texture(skybox, rayDirection).rgb;
    imageStore(imgOutput, _texelCord, vec4(skyBoxColour, 1.0));
}

void main() {
    
    vec2 imgSize = imageSize(imgOutput);
    ivec2 texelCord = GetTexelCoordinate();
    vec2 uv = (vec2(texelCord) + 0.5) / imgSize;

    if(IsInsideWindow(imgSize, texelCord)) return;

    Raytrace(camera, imgSize, texelCord, uv);
}