#version 450 core
#define PI 3.14159265359

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

struct DDARay{
    ivec3 currentCell; // cell ray is in
    ivec3 stepDirection; // direction of stepping (1 or -1) in each axis
    vec3 tMax; // Distance to next boundry
    vec3 tDelta; // Distance between current boundry and new boundry
    float t; // Distance parameter | pos(t) = origin * direction * t
};

struct Camera{
    vec3 position;
    vec3 up;
    vec3 right;
    vec3 front;
    float fov;
    float maxRayLength;
};

struct Sphere{
    vec3 position;
    float radius;
};

struct Particle{
    vec3 position;
    float radius;
    vec3 velocity;
    float mass;
    vec4 color;
};
layout(std430, binding = 0) buffer particleBuffer {Particle particles[];};

struct GridEntry{
    uint cellIndex;
    uint particleIndex;
};
layout(std430, binding = 1) buffer cellEntryBuffer { GridEntry entries[]; };

layout(std430, binding = 2) buffer cellStartBuffer { 
    uint cellStart[];
};

layout(std430, binding = 3) buffer cellEndBuffer {
    uint cellEnd[];
};

// Image binding
layout (rgba32f, binding = 0) uniform image2D imgOutput;
// Texture binding
layout(binding = 0) uniform samplerCube skybox;
// SSBO binding

// Uniform binding
uniform float cellSize;
uniform float particleRadius;
uniform ivec3 gridSize;
uniform vec3 gridMin;
uniform Camera camera;
uniform Sphere sphere;
// Constants
const uint INVALID = 0xffffffffu;
vec4 blackHoleColor = vec4(0.0, 0.0, 0.0, 1.0);
const int cellRadius = int(ceil(particleRadius / cellSize)); // allows for particle radius to be greater than cell size, although expensive

bool PixelIsInput(vec2 _pixel, vec2 _position)
{
    return _pixel == _position;
}

ivec2 UVToPixel(vec2 _uv, ivec2 _imgSize)
{
    return ivec2(_uv * vec2(_imgSize - 1));
}

ivec2 GetTexelCoordinate()
{
    return ivec2(gl_GlobalInvocationID.xy);
}

bool IsInsideWindow(vec2 _imageSize, ivec2 _texelCord){
    if (_texelCord.x >= _imageSize.x ||
        _texelCord.y >= _imageSize.y)
    {
        return true;
    }
    return false;
}

DDARay InitDDA(vec3 _rayOrigin, vec3 _rayDirection)
{
    DDARay dda;

    // finds the inital position -> cell of dda checking for landing on axis edge
    vec3 pos = (_rayOrigin - gridMin) / cellSize;
    dda.currentCell = ivec3(floor(pos));
    if (_rayDirection.x < 0.0 && fract(pos.x) == 0.0)
        dda.currentCell.x--;
    if (_rayDirection.y < 0.0 && fract(pos.y) == 0.0)
        dda.currentCell.y--;
    if (_rayDirection.z < 0.0 && fract(pos.z) == 0.0)
        dda.currentCell.z--;

    // Direction of grid traversal
    dda.stepDirection = ivec3(
        _rayDirection.x >= 0.0 ? 1 : -1,
        _rayDirection.y >= 0.0 ? 1 : -1,
        _rayDirection.z >= 0.0 ? 1 : -1
    );

    // Distance along ray between boundries
    dda.tDelta = vec3(
        _rayDirection.x != 0.0 ? abs(cellSize / _rayDirection.x) : 1.0 / 0.0,
        _rayDirection.y != 0.0 ? abs(cellSize / _rayDirection.y) : 1.0 / 0.0,
        _rayDirection.z != 0.0 ? abs(cellSize / _rayDirection.z) : 1.0 / 0.0
    );

    // Find next grid boundry on each axis
    vec3 cellMin = gridMin + vec3(dda.currentCell) * cellSize;
    vec3 cellMax = cellMin + vec3(cellSize);
    vec3 nextBoundary = vec3(
        dda.stepDirection.x > 0 ? cellMax.x : cellMin.x,
        dda.stepDirection.y > 0 ? cellMax.y : cellMin.y,
        dda.stepDirection.z > 0 ? cellMax.z : cellMin.z
    );

    // this is what usese the ray equation | P(t) = origin + direction * t | re arranged for t -> | t = (nextBoundary.x - origin.x) / direction.x |
    // depending on what is least, that is the boundry hit
    dda.tMax = vec3(
        _rayDirection.x != 0.0 ? (nextBoundary.x - _rayOrigin.x) / _rayDirection.x : 1.0 / 0.0,
        _rayDirection.y != 0.0 ? (nextBoundary.y - _rayOrigin.y) / _rayDirection.y : 1.0 / 0.0,
        _rayDirection.z != 0.0 ? (nextBoundary.z - _rayOrigin.z) / _rayDirection.z : 1.0 / 0.0
    );

    dda.t = 0.0;

    return dda;
}

void AdvanceDDA(inout DDARay _dda)
{
    // checks to find the closest boundry, whichever boundry has the closer axis wins.
    if (_dda.tMax.x <= _dda.tMax.y &&
        _dda.tMax.x <= _dda.tMax.z)
    {
        _dda.t = _dda.tMax.x; // record crossing position
        _dda.tMax.x += _dda.tDelta.x; // update max boundry distance
        _dda.currentCell.x += _dda.stepDirection.x; // update current cell
    }
    else if (_dda.tMax.y <= _dda.tMax.z)
    {
        _dda.t = _dda.tMax.y;
        _dda.tMax.y += _dda.tDelta.y;
        _dda.currentCell.y += _dda.stepDirection.y;
    }
    else
    {
        _dda.t = _dda.tMax.z;
        _dda.tMax.z += _dda.tDelta.z;
        _dda.currentCell.z += _dda.stepDirection.z;
    }
}

bool RaySphereIntersection(vec3 _rayOrigin, vec3 _rayDirection, Sphere _sphere, float _tMin, float _tMax, out float _hitT)
{
    vec3 oc = _rayOrigin - _sphere.position;

    float b = dot(oc, _rayDirection);
    float c = dot(oc, oc) - _sphere.radius * _sphere.radius;

    float discriminant = b * b - c;

    if(discriminant < 0.0)
        return false;
    
    float sqrtD = sqrt(discriminant);

    float t0 = -b - sqrtD;
    float t1 = -b + sqrtD;

    // find first intersection within cell segement
    float t = t0;

    if(t < _tMin)
        t = t1;
    
    if(t < _tMin || t > _tMax)
        return false;
    
    _hitT = t;
    return true;
}

bool SphereAABB(vec3 _sCenter, float _sRadius, vec3 _abMin, vec3 _abMax)
{
    const float x = max(_abMin.x, min(_sCenter.x, _abMax.x));
    const float y = max(_abMin.y, min(_sCenter.y, _abMax.y));
    const float z = max(_abMin.z, min(_sCenter.z, _abMax.z));

    const float dx = _sCenter.x - x;
    const float dy = _sCenter.y - y;
    const float dz = _sCenter.z - z;

    return dx * dx + dy * dy + dz * dz <= _sRadius * _sRadius;
}

bool RayAABB(vec3 _rayOrigin, vec3 _rayDirection, vec3 _boxMin, vec3 _boxMax, float _tMin, float _tMax)
{
    vec3 invDir = 1.0 / _rayDirection;

    vec3 t0 = (_boxMin - _rayOrigin) * invDir;
    vec3 t1 = (_boxMax - _rayOrigin) * invDir;

    vec3 tNear = min(t0, t1);
    vec3 tFar  = max(t0, t1);

    float nearT = max(_tMin, max(tNear.x, max(tNear.y, tNear.z)));
    float farT  = min(_tMax, min(tFar.x, min(tFar.y, tFar.z)));

    return nearT <= farT;
}

bool RayCapsuleAABB(vec3 _rayOrigin, vec3 _rayDirection, vec3 _cellMin, vec3 _cellMax, float _tMin, float _tMax, float _radius)
{
    _cellMin -= vec3(_radius);
    _cellMax += vec3(_radius);

    return RayAABB(_rayOrigin, _rayDirection, _cellMin, _cellMax, _tMin, _tMax);
}

vec2 DirectionToUV(vec3 _dir)
{
    float u = atan(_dir.y, _dir.x) / (2.0 * PI) + 0.5;
    float v = asin(_dir.z) / PI + 0.5;

    return vec2(u, v);
}

bool FindParticleHit(uint _cellIndex, vec3 _rayOrigin, vec3 _rayDirection, float _tMin, float _tMax, inout float _closestHit, inout uint _closestParticle)
{
    uint start = cellStart[_cellIndex];
    uint end   = cellEnd[_cellIndex];

    for (uint i = start; i < end; ++i)
    {
        uint particleIndex = entries[i].particleIndex;

        if (particleIndex == 0xffffffff)
            continue;

        Sphere particleSphere;
        particleSphere.position = particles[particleIndex].position;
        particleSphere.radius = particles[particleIndex].radius;
        float hitT;
        if (RaySphereIntersection(_rayOrigin, _rayDirection, particleSphere, _tMin, min(_tMax, _closestHit), hitT))
        {
            if (hitT < _closestHit)
            {
                _closestHit = hitT;
                _closestParticle = particleIndex;
            }
        }
    }

    return _closestParticle != 0xffffffff;
}

bool InsideGrid(ivec3 _c)
{
    return
        _c.x >= 0 &&
        _c.y >= 0 &&
        _c.z >= 0 &&
        _c.x < gridSize.x &&
        _c.y < gridSize.y &&
        _c.z < gridSize.z;
}

uint GridIndex(ivec3 _c)
{
    return uint(
        _c.x +
        _c.y * gridSize.x +
        _c.z * gridSize.x * gridSize.y
    );
}

void Raytrace(const Camera _camera, vec2 _imageSize, ivec2 _texelCord, vec2 _uv)
{
    // Ray generation
    // ------------------
    vec2 centredUV = (_uv * 2.0) - 1.0;
    float fov = tan(radians(_camera.fov) * 0.5);
    centredUV *= fov;

    float aspect = _imageSize.x / _imageSize.y;
    centredUV.x *= aspect;

    vec3 rayDirection = normalize(
        _camera.front +
        centredUV.x * _camera.right +
        centredUV.y * _camera.up
    );

    vec3 rayOrigin = _camera.position;

    // Black hole intersection
    // --------------------------------
    float blackHoleT;
    bool blackHoleHit = RaySphereIntersection(rayOrigin, rayDirection, sphere, 0.0, _camera.maxRayLength, blackHoleT);

    // DDA initialization
    // -----------------------

    DDARay dda = InitDDA(rayOrigin, rayDirection);

    // Don't search beyond black hole
    float rayEnd = _camera.maxRayLength;

    if (blackHoleHit)
        rayEnd = min(rayEnd, blackHoleT);
    vec3 skyBoxColour = texture(skybox, rayDirection).rgb;  
    // Traverse grid
    // --------------------
    while (dda.t < rayEnd)
    {
        float cellExitT = min(dda.tMax.x, min(dda.tMax.y, dda.tMax.z));
        cellExitT = min(cellExitT, rayEnd);

        
        // Search current + neighbouring cells
        // -------------------------------------
        float closestHit = cellExitT;
        uint closestParticle = 0xffffffff;
        //SearchNeighbourCells(dda.currentCell, rayOrigin, rayDirection, dda.t, cellExitT, closestHit, closestParticle);
        
        ivec3 cell = dda.currentCell;

        if (!InsideGrid(cell))
        {
            // ray left simulation volume
            break;
        }

        uint cellIndex = GridIndex(cell);
        uint start = cellStart[cellIndex];

        if (start != INVALID)
        {
            imageStore(imgOutput, _texelCord, vec4(skyBoxColour, 1.0));
            FindParticleHit(cellIndex, rayOrigin, rayDirection, dda.t, cellExitT, closestHit, closestParticle);
        }

        // Particle hit
        // -------------------
        if (closestParticle != 0xffffffff)
        {
            imageStore(imgOutput, _texelCord, particles[closestParticle].color);
            return;
        }

        // Black hole reached
        // -----------------------
        if (blackHoleHit && blackHoleT <= cellExitT)
        {
            imageStore(imgOutput, _texelCord, blackHoleColor);
            return;
        }

        // Next grid cell
        // ------------------
        AdvanceDDA(dda);
    }

    // Nothing hit
    // ----------------
    if (blackHoleHit)
    {
        imageStore(imgOutput, _texelCord, blackHoleColor);
        return;
    }

    //vec3 skyBoxColour = texture(skybox, rayDirection).rgb;
    //imageStore(imgOutput, _texelCord, vec4(skyBoxColour, 1.0));
}

void main() {
    
    vec2 imgSize = imageSize(imgOutput);
    ivec2 texelCord = GetTexelCoordinate();
    vec2 uv = (vec2(texelCord) + 0.5) / imgSize;

    if(IsInsideWindow(imgSize, texelCord)) return;

    Raytrace(camera, imgSize, texelCord, uv);
}