#version 450 core

layout (local_size_x = 10, local_size_y = 1, local_size_z = 1) in;

struct Particle{
    vec3 position;
    float radius;
    vec3 velocity;
    float mass;
};
layout (std430, binding = 0)
buffer particleBuffer {
    Particle particles[];
};

int GetParticleIndex()
{
    return int(gl_GlobalInvocationID.x);
}

uint Hash(ivec3 _c)
{
    const uint h1 = 798016u;
    const uint h2 = 625481u;
    const uint h3 = 321930u;
    // XOR ^ mixes the bits togeather better than with addition or othewise, good for hasing.
    return _c.x * h1 ^_c.y * h2 ^_c.z * h3;
}

void main() {
    int id = GetParticleIndex();
    //float cellSize = smoothingRadius;
    //// 1. Hash particles
    //particles[id].hash = Hash(particles[id].position/cellSize);

    // 2. Sort by hash

    // 3. build cell start / end
}

