#version 450 core

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct HashEntry{
    uint hash;
    uint particleIndex;
};
layout(std430, binding = 1)
buffer hashBuffer {
    HashEntry hashes[];
};

uniform int activeCount;
uniform int k;
uniform int j;

int GetIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, int _count){
    if(_id >= _count)
        return false;
    return true;
}

void SwapHashIndex(int _a, int _b)
{
    HashEntry temp = hashes[_a];
    hashes[_a] = hashes[_b];
    hashes[_b] = temp;
}

void main() {
    
    int id = GetIndex();
    if(!WithinBounds(id, hashes.length()))
        return;

    // Useses bitwise XOR to find partner
    // Example id = 5 = 0101
    // Exmaple j = 4 = 0100
    // Exmaple partner = 1 = 0001
    int partner = id ^ j; 
    //if(!WithinBounds(partner, activeCount))
    //    return;

    // end early if overlappign sort, 4 sort with 0 and 0 sort with 4, so lower bounds is droped.
    if(id > partner)
        return;

    // Bitonic sort goes 1234321 for optiomal sorting, this makes sure this happens. 
    bool ascending = ((id & k) == 0);

    if(ascending)
    {
        if(hashes[id].hash > hashes[partner].hash){
            HashEntry temp = hashes[id];
            hashes[id] = hashes[partner];
            hashes[partner] = temp;
        }
    } else {
        if(hashes[id].hash < hashes[partner].hash){
            HashEntry temp = hashes[id];
            hashes[id] = hashes[partner];
            hashes[partner] = temp;
        }
    }

}