#version 450 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct HashEntry
{
    uint hash;
    uint index;
};
layout(std430, binding = 1) readonly buffer EntryBuffer
{
    HashEntry entries[];
};

layout(std430, binding = 2) writeonly buffer CellStartBuffer
{
    uint cellStart[];
};

layout(std430, binding = 3) writeonly buffer CellEndBuffer
{
    uint cellEnd[];
};

layout(std430, binding = 6) readonly buffer FlagBuffer
{
    uint flags[];
};

uniform int activeCount;
const uint INVALID = 0xffffffffu;

int GetIndex()
{
    return int(gl_GlobalInvocationID.x);
}

bool WithinBounds(int _id, int _count){
    if(_id >= _count)
        return false;
    return true;
}

void main()
{
    int id = GetIndex();

    if (!WithinBounds(id, activeCount))
        return;

    uint cell = entries[id].hash;

    if (cell == INVALID)
        return;

    // Start of cell
    if (flags[id] == 1u)
    {
        cellStart[cell] = id;
    }

    // End of cell
    if (id == uint(activeCount - 1) ||
        flags[id + 1u] == 1u)
    {
        cellEnd[cell] = id + 1u;
    }
}